import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/app/providers";

export const metadata: Metadata = {
  title: "EzStocks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://kit.fontawesome.com/ad98de5722.js" crossOrigin="anonymous"></script>
      </head>
      <body>
		<Providers>
			{children}
		</Providers>
		</body>
    </html>
  );
}
